### ISSUE TITLE
ScaleIOPersistentVolumeSource not available in release-1.8.2 tag & release-1.8 branch.

### ISSUE THREAD

**Issue by chakri-nelluri** [kubernetes/api#12]
# k8s.io/kubernetes/pkg/api/v1
../../../.go/src/k8s.io/kubernetes/pkg/api/v1/defaults.go:380: undefined: "k8s.io/api/core/v1".ScaleIOPersistentVolumeSource
../../../.go/src/k8s.io/kubernetes/pkg/api/v1/zz_generated.conversion.go:3172: undefined: "k8s.io/api/core/v1".ScaleIOPersistentVolumeSource
../../../.go/src/k8s.io/kubernetes/pkg/api/v1/zz_generated.conversion.go:4463: undefined: "k8s.io/api/core/v1".ScaleIOPersistentVolumeSource
../../../.go/src/k8s.io/kubernetes/pkg/api/v1/zz_generated.conversion.go:4478: undefined: "k8s.io/api/core/v1".ScaleIOPersistentVolumeSource
../../../.go/src/k8s.io/kubernetes/pkg/api/v1/zz_generated.conversion.go:4482: undefined: "k8s.io/api/core/v1".ScaleIOPersistentVolumeSource
../../../.go/src/k8s.io/kubernetes/pkg/api/v1/zz_generated.conversion.go:4497: undefined: "k8s.io/api/core/v1".ScaleIOPersistentVolumeSource
make[3]: *** [armada/armada] Error 2

**Comment by nikhita** [comment]
@chakri-nelluri It is present in on the release-1.8 branch and release-1.8.4 tag now.

The syncing from staging was broken before, that's why you probably saw this. It is back in action with https://github.com/kubernetes/publishing-bot. Closing. Please reopen if you feel an issue still persists.

/close
