### ISSUE TITLE
Pods unable to reach kubernetes API on EKS

### ISSUE THREAD

**Issue by jonesg504** [kubernetes/api#24]
I have a coreDNS deployment that is unable to reach the kubernetes api
```
E0408 16:39:27.779433       1 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:355: Failed to list *v1.Namespace: Get https://10.100.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.100.0.1:443: i/o timeout
E0408 16:39:27.779861       1 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:348: Failed to list *v1.Service: Get https://10.100.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.100.0.1:443: i/o timeout
E0408 16:39:27.779928       1 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:350: Failed to list *v1.Endpoints: Get https://10.100.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.100.0.1:443: i/o timeout
E0408 16:39:58.781491       1 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:355: Failed to list *v1.Namespace: Get https://10.100.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.100.0.1:443: i/o timeout
E0408 16:39:58.781715       1 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:348: Failed to list *v1.Service: Get https://10.100.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.100.0.1:443: i/o timeout
E0408 16:39:58.782838       1 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:350: Failed to list *v1.Endpoints: Get https://10.100.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.100.0.1:443: i/o timeout
E0408 16:40:29.782060       1 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:355: Failed to list *v1.Namespace: Get https://10.100.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.100.0.1:443: i/o timeout
E0408 16:40:29.784090       1 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:348: Failed to list *v1.Service: Get https://10.100.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.100.0.1:443: i/o timeout
E0408 16:40:29.784374       1 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:350: Failed to list *v1.Endpoints: Get https://10.100.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.100.0.1:443: i/o timeout
2019/04/08 16:40:37 [INFO] SIGTERM: Shutting down servers then terminating
```
Im running EKS, it has one worker node so everything should be running on the same EC2 instance. I have been unable to access the kubernetes api logs due to some permission issues, any advice or suggestions would be appreciated.

**Comment by nikhita** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes)
or our [Discussion Forums](https://discuss.kubernetes.io).

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on GitHub is making it difficult for us to use
issues to identify real bugs.

Members of the Kubernetes community use Stack Overflow and Discussion Forums to field
support requests. Before posting a new question, please search these for answers
to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/home/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team
