### ISSUE TITLE
`PodFailurePolicyRule` fails to validate if `onPodConditions` is not set.

### ISSUE THREAD

**Issue by Tanemahuta** [kubernetes/api#48]
As stated in the docs https://github.com/kubernetes/api/blob/2f9553831ec24dc60e3e1c3a374fb63ca091688f/batch/v1/types.go#L182
one of fields must be present.

But 
https://github.com/kubernetes/api/blob/2f9553831ec24dc60e3e1c3a374fb63ca091688f/batch/v1/types.go#L204 
lacks `+optional`. This, the OpenAPI validation fails, if `onPodConditions` is not set.

Background: we are using kyverno, which uses the OpenAPI validation after applying a policy.

**Comment by xxnpark** [comment]
Here with the same problem.

`onPodConditions` is not required, rather it is a `repeated` field in protobuf but the OpenAPI docs states it as 'required'.

https://github.com/kubernetes/api/blob/8a20f1bdac2dc813e2cc9afecf57cc3a45156e22/batch/v1/generated.proto#L533

Similarly, `rules` in `podFailurePolicy` has the same issue.
https://github.com/kubernetes/api/blob/8a20f1bdac2dc813e2cc9afecf57cc3a45156e22/batch/v1/types.go#L249-L250

---
Background

I originally encountered a problem in the kubernetes Python client, reported here: https://github.com/kubernetes-client/python/issues/2056. The problem seems to originate from this issue.

The Python codes are genererated from OpenAPI using [openapi-generator](https://openapi-generator.tech/), so validation fails when we don't specify `onPodConditions` in the spec.
