### ISSUE TITLE
The Golang version of version v0.30.0 specifced  in the mod file is a precise verson number 

### ISSUE THREAD

**Issue by YanniHu1996** [kubernetes/api#74]
Hi Team, 

Let's see https://github.com/kubernetes/api/blob/v0.30.0/go.mod
```
// This is a generated file. Do not edit directly.

module k8s.io/api

go 1.22.0
```

Please take into account that the Go version specified in the v0.30.0 mod file is 1.22.0. Consequently, it necessitates that any Golang modules relying on v0.30.0 must also adhere to the precise Golang version number

is it possible to use the Golang version without the patch number in later versions? For example https://github.com/kubernetes/api/blob/v0.29.4/go.mod

**Comment by dagraff-cisco** [comment]
maybe apply a little `go mod edit -go=1.22 -toolchain=go1.22.0`?

**Comment by dagraff-cisco** [comment]
Would it be possible to get this fixed sooner than later? My enterprise Snyk scan is flagging this and hitting us with a number of vulnerabilities because of it. We're building our application currently with golang 1.22.5+ however because of this item, the Snyk scan is flagging the entire thing as being vulnerable.

**Comment by dims** [comment]
let's use https://github.com/kubernetes/kubernetes/issues/126636

/close
